// Code generated by scripts/generate-platform-tokens.mjs; DO NOT EDIT.
// Source: tokens/bytedesk.tokens.json
// Source SHA-256: 9cef3545f14533db2eb75b27a807dfff06855b4c7205f786d2e90890ed1de857

pub const TOKEN_SOURCE_SHA256: &str = "9cef3545f14533db2eb75b27a807dfff06855b4c7205f786d2e90890ed1de857";

pub const BREAKPOINT_COMPACT_MAX: &str = "719px";
pub const BREAKPOINT_STANDARD_MIN: &str = "720px";
pub const BREAKPOINT_ULTRAWIDE_MIN: &str = "1600px";
pub const BREAKPOINT_WIDE_MIN: &str = "1200px";
pub const COLOR_ACCENT_DEFAULT: &str = "#0079F2";
pub const COLOR_ACCENT_EMPHASIS: &str = "#468CE8";
pub const COLOR_ACCENT_FG: &str = "#E8F1FB";
pub const COLOR_ACCENT_MUTED: &str = "#255DA5";
pub const COLOR_ACCENT_SUBTLE: &str = "#193356";
pub const COLOR_BG_BASE: &str = "#0F1017";
pub const COLOR_BG_ELEVATED: &str = "#2A2C37";
pub const COLOR_BG_OVERLAY: &str = "#343742";
pub const COLOR_BG_SUBTLE: &str = "#1A1C25";
pub const COLOR_BG_SURFACE: &str = "#23252F";
pub const COLOR_BLUE_100: &str = "#0E2037";
pub const COLOR_BLUE_200: &str = "#193356";
pub const COLOR_BLUE_300: &str = "#1F487C";
pub const COLOR_BLUE_400: &str = "#255DA5";
pub const COLOR_BLUE_50: &str = "#071221";
pub const COLOR_BLUE_500: &str = "#0079F2";
pub const COLOR_BLUE_600: &str = "#468CE8";
pub const COLOR_BLUE_700: &str = "#71A7EF";
pub const COLOR_BLUE_800: &str = "#9CC0F1";
pub const COLOR_BLUE_900: &str = "#C7D9F2";
pub const COLOR_BORDER_DEFAULT: &str = "#3A3D48";
pub const COLOR_BORDER_DIMMER: &str = "#31343F";
pub const COLOR_BORDER_DIMMEST: &str = "#252732";
pub const COLOR_BORDER_STRONGER: &str = "#444752";
pub const COLOR_BORDER_STRONGEST: &str = "#4D505C";
pub const COLOR_BRAND_ORANGE: &str = "#EC4E02";
pub const COLOR_BRAND_ORANGE_MUTED: &str = "#D96D00";
pub const COLOR_CHART_AXIS: &str = "#A2A8B2";
pub const COLOR_CHART_GRID: &str = "#31343F";
pub const COLOR_CHART_PLOT: &str = "#1A1C25";
pub const COLOR_CHART_SELECTION: &str = "#468CE8";
pub const COLOR_CHART_SERIES_1: &str = "#0079F2";
pub const COLOR_CHART_SERIES_2: &str = "#1DB8CE";
pub const COLOR_CHART_SERIES_3: &str = "#A170EB";
pub const COLOR_CHART_SERIES_4: &str = "#EA5DA9";
pub const COLOR_CHART_SERIES_5: &str = "#EC4E02";
pub const COLOR_CHART_SERIES_6: &str = "#009118";
pub const COLOR_CHART_SERIES_7: &str = "#DFA700";
pub const COLOR_CHART_SERIES_8: &str = "#E52222";
pub const COLOR_DESK_AGENTIC: &str = "#1B3060";
pub const COLOR_DESK_DEVELOPER: &str = "#2F2D55";
pub const COLOR_DESK_FILES: &str = "#013752";
pub const COLOR_DESK_PROJECTS: &str = "#282F56";
pub const COLOR_DESK_SESSIONS: &str = "#193356";
pub const COLOR_DESK_SYSTEM: &str = "#1D354B";
pub const COLOR_INTERACTIVE_BLUE: &str = "#0079F2";
pub const COLOR_INTERACTIVE_FOCUS: &str = "#71A7EF";
pub const COLOR_SEMANTIC_DANGER: &str = "#E52222";
pub const COLOR_SEMANTIC_DANGER_BG: &str = "#2A1212";
pub const COLOR_SEMANTIC_DANGER_LINE: &str = "#7A2424";
pub const COLOR_SEMANTIC_INFO: &str = "#1DB8CE";
pub const COLOR_SEMANTIC_INFO_BG: &str = "#0C2226";
pub const COLOR_SEMANTIC_INFO_LINE: &str = "#1A5A64";
pub const COLOR_SEMANTIC_SUCCESS: &str = "#009118";
pub const COLOR_SEMANTIC_SUCCESS_BG: &str = "#0C2414";
pub const COLOR_SEMANTIC_SUCCESS_LINE: &str = "#165C22";
pub const COLOR_SEMANTIC_SUCCESS_MUTED: &str = "#007012";
pub const COLOR_SEMANTIC_WARNING: &str = "#DFA700";
pub const COLOR_SEMANTIC_WARNING_BG: &str = "#241E0C";
pub const COLOR_SEMANTIC_WARNING_LINE: &str = "#6B5A14";
pub const COLOR_TEXT_DISABLED: &str = "#6B7280";
pub const COLOR_TEXT_ON_BRAND: &str = "#FFE2D8";
pub const COLOR_TEXT_PRIMARY: &str = "#E6E8ED";
pub const COLOR_TEXT_SECONDARY: &str = "#BFC4CA";
pub const COLOR_TEXT_TERTIARY: &str = "#A2A8B2";
pub const FONT_DISPLAY: &str = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]";
pub const FONT_MONO: &str = "[\"IBM Plex Mono\",\"ui-monospace\",\"SFMono-Regular\",\"monospace\"]";
pub const FONT_SANS: &str = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]";
pub const FONTWEIGHT_BOLD: &str = "700";
pub const FONTWEIGHT_MEDIUM: &str = "500";
pub const FONTWEIGHT_REGULAR: &str = "400";
pub const FONTWEIGHT_SEMIBOLD: &str = "600";
pub const LETTERSPACING_CAPS: &str = "0.08em";
pub const LETTERSPACING_LABEL: &str = "0.04em";
pub const LETTERSPACING_TIGHT: &str = "-0.02em";
pub const LINEHEIGHT_BODY: &str = "1.5";
pub const LINEHEIGHT_COMPACT: &str = "1.35";
pub const LINEHEIGHT_TIGHT: &str = "1.2";
pub const MOTION_DURATION_BASE: &str = "250ms";
pub const MOTION_DURATION_FAST: &str = "150ms";
pub const MOTION_DURATION_SLOW: &str = "400ms";
pub const MOTION_EASE_OUT_EXPO: &str = "[0.16,1,0.3,1]";
pub const OPACITY_DISABLED: &str = "0.5";
pub const OPACITY_HOVER: &str = "0.08";
pub const OPACITY_SCRIM: &str = "0.72";
pub const OPACITY_SECONDARY: &str = "0.72";
pub const PRODUCT_AGENT_BROWSER: &str = "#1DB8CE";
pub const PRODUCT_AGENT_MEMORY: &str = "#EA5DA9";
pub const PRODUCT_CAPTURE: &str = "#0A84FF";
pub const PRODUCT_GATEWAY: &str = "#0079F2";
pub const PRODUCT_PLATFORM: &str = "#EC4E02";
pub const PRODUCT_STORE: &str = "#009118";
pub const PRODUCT_TOOLBOX: &str = "#7C8AE8";
pub const PRODUCT_VAULT: &str = "#DFA700";
pub const PRODUCT_WORKFORCE: &str = "#A170EB";
pub const RADIUS_2XL: &str = "16px";
pub const RADIUS_FULL: &str = "9999px";
pub const RADIUS_LG: &str = "8px";
pub const RADIUS_MD: &str = "6px";
pub const RADIUS_SM: &str = "4px";
pub const RADIUS_XL: &str = "12px";
pub const SIZE_CHART_MINIMUM_HEIGHT: &str = "180px";
pub const SIZE_CHART_POINT: &str = "6px";
pub const SIZE_CONTROL_COMPACT: &str = "28px";
pub const SIZE_CONTROL_DEFAULT: &str = "32px";
pub const SIZE_CONTROL_TOUCH: &str = "44px";
pub const SIZE_HIT_TARGET_POINTER: &str = "28px";
pub const SIZE_HIT_TARGET_TOUCH: &str = "44px";
pub const SIZE_ICON_LG: &str = "20px";
pub const SIZE_ICON_MD: &str = "16px";
pub const SIZE_ICON_SM: &str = "14px";
pub const SIZE_ICON_XL: &str = "24px";
pub const SIZE_PANEL_COMFORTABLE: &str = "360px";
pub const SIZE_PANEL_MINIMUM: &str = "280px";
pub const SIZE_PANEL_WIDE: &str = "480px";
pub const SIZE_ROW_COMPACT: &str = "28px";
pub const SIZE_ROW_DEFAULT: &str = "32px";
pub const SIZE_ROW_TOUCH: &str = "44px";
pub const SIZE_SHELL_COMMANDBAR: &str = "36px";
pub const SIZE_SHELL_INSPECTOR: &str = "360px";
pub const SIZE_SHELL_RAIL: &str = "48px";
pub const SIZE_SHELL_SIDEBAR: &str = "196px";
pub const SIZE_SHELL_STATUSBAR: &str = "24px";
pub const SIZE_SHELL_TOPBAR: &str = "44px";
pub const SIZE_TERMINAL_TAB: &str = "32px";
pub const SPACE_0: &str = "0px";
pub const SPACE_1: &str = "2px";
pub const SPACE_10: &str = "40px";
pub const SPACE_11: &str = "48px";
pub const SPACE_2: &str = "4px";
pub const SPACE_3: &str = "6px";
pub const SPACE_4: &str = "8px";
pub const SPACE_5: &str = "12px";
pub const SPACE_6: &str = "16px";
pub const SPACE_7: &str = "20px";
pub const SPACE_8: &str = "24px";
pub const SPACE_9: &str = "32px";
pub const STROKE_ACTIVE: &str = "2px";
pub const STROKE_CHART: &str = "2px";
pub const STROKE_FOCUS: &str = "2px";
pub const STROKE_HAIRLINE: &str = "1px";
pub const TYPE_BODY: &str = "15px";
pub const TYPE_BODY_LG: &str = "17px";
pub const TYPE_BODY_SM: &str = "13px";
pub const TYPE_CAPTION: &str = "11px";
pub const TYPE_CONSOLE: &str = "12.5px";
pub const TYPE_CONSOLE_SM: &str = "11px";
pub const TYPE_DISPLAY: &str = "40px";
pub const TYPE_H1: &str = "32px";
pub const TYPE_H2: &str = "24px";
pub const TYPE_H3: &str = "20px";
pub const TYPE_H4: &str = "18px";

pub const ALL: &[(&str, &str)] = &[
    ("breakpoint.compact-max", "719px"),
    ("breakpoint.standard-min", "720px"),
    ("breakpoint.ultrawide-min", "1600px"),
    ("breakpoint.wide-min", "1200px"),
    ("color.accent.default", "#0079F2"),
    ("color.accent.emphasis", "#468CE8"),
    ("color.accent.fg", "#E8F1FB"),
    ("color.accent.muted", "#255DA5"),
    ("color.accent.subtle", "#193356"),
    ("color.bg.base", "#0F1017"),
    ("color.bg.elevated", "#2A2C37"),
    ("color.bg.overlay", "#343742"),
    ("color.bg.subtle", "#1A1C25"),
    ("color.bg.surface", "#23252F"),
    ("color.blue.100", "#0E2037"),
    ("color.blue.200", "#193356"),
    ("color.blue.300", "#1F487C"),
    ("color.blue.400", "#255DA5"),
    ("color.blue.50", "#071221"),
    ("color.blue.500", "#0079F2"),
    ("color.blue.600", "#468CE8"),
    ("color.blue.700", "#71A7EF"),
    ("color.blue.800", "#9CC0F1"),
    ("color.blue.900", "#C7D9F2"),
    ("color.border.default", "#3A3D48"),
    ("color.border.dimmer", "#31343F"),
    ("color.border.dimmest", "#252732"),
    ("color.border.stronger", "#444752"),
    ("color.border.strongest", "#4D505C"),
    ("color.brand.orange", "#EC4E02"),
    ("color.brand.orange-muted", "#D96D00"),
    ("color.chart.axis", "#A2A8B2"),
    ("color.chart.grid", "#31343F"),
    ("color.chart.plot", "#1A1C25"),
    ("color.chart.selection", "#468CE8"),
    ("color.chart.series-1", "#0079F2"),
    ("color.chart.series-2", "#1DB8CE"),
    ("color.chart.series-3", "#A170EB"),
    ("color.chart.series-4", "#EA5DA9"),
    ("color.chart.series-5", "#EC4E02"),
    ("color.chart.series-6", "#009118"),
    ("color.chart.series-7", "#DFA700"),
    ("color.chart.series-8", "#E52222"),
    ("color.desk.agentic", "#1B3060"),
    ("color.desk.developer", "#2F2D55"),
    ("color.desk.files", "#013752"),
    ("color.desk.projects", "#282F56"),
    ("color.desk.sessions", "#193356"),
    ("color.desk.system", "#1D354B"),
    ("color.interactive.blue", "#0079F2"),
    ("color.interactive.focus", "#71A7EF"),
    ("color.semantic.danger", "#E52222"),
    ("color.semantic.danger-bg", "#2A1212"),
    ("color.semantic.danger-line", "#7A2424"),
    ("color.semantic.info", "#1DB8CE"),
    ("color.semantic.info-bg", "#0C2226"),
    ("color.semantic.info-line", "#1A5A64"),
    ("color.semantic.success", "#009118"),
    ("color.semantic.success-bg", "#0C2414"),
    ("color.semantic.success-line", "#165C22"),
    ("color.semantic.success-muted", "#007012"),
    ("color.semantic.warning", "#DFA700"),
    ("color.semantic.warning-bg", "#241E0C"),
    ("color.semantic.warning-line", "#6B5A14"),
    ("color.text.disabled", "#6B7280"),
    ("color.text.on-brand", "#FFE2D8"),
    ("color.text.primary", "#E6E8ED"),
    ("color.text.secondary", "#BFC4CA"),
    ("color.text.tertiary", "#A2A8B2"),
    ("font.display", "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"),
    ("font.mono", "[\"IBM Plex Mono\",\"ui-monospace\",\"SFMono-Regular\",\"monospace\"]"),
    ("font.sans", "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"),
    ("fontWeight.bold", "700"),
    ("fontWeight.medium", "500"),
    ("fontWeight.regular", "400"),
    ("fontWeight.semibold", "600"),
    ("letterSpacing.caps", "0.08em"),
    ("letterSpacing.label", "0.04em"),
    ("letterSpacing.tight", "-0.02em"),
    ("lineHeight.body", "1.5"),
    ("lineHeight.compact", "1.35"),
    ("lineHeight.tight", "1.2"),
    ("motion.duration-base", "250ms"),
    ("motion.duration-fast", "150ms"),
    ("motion.duration-slow", "400ms"),
    ("motion.ease-out-expo", "[0.16,1,0.3,1]"),
    ("opacity.disabled", "0.5"),
    ("opacity.hover", "0.08"),
    ("opacity.scrim", "0.72"),
    ("opacity.secondary", "0.72"),
    ("product.agent-browser", "#1DB8CE"),
    ("product.agent-memory", "#EA5DA9"),
    ("product.capture", "#0A84FF"),
    ("product.gateway", "#0079F2"),
    ("product.platform", "#EC4E02"),
    ("product.store", "#009118"),
    ("product.toolbox", "#7C8AE8"),
    ("product.vault", "#DFA700"),
    ("product.workforce", "#A170EB"),
    ("radius.2xl", "16px"),
    ("radius.full", "9999px"),
    ("radius.lg", "8px"),
    ("radius.md", "6px"),
    ("radius.sm", "4px"),
    ("radius.xl", "12px"),
    ("size.chart.minimum-height", "180px"),
    ("size.chart.point", "6px"),
    ("size.control.compact", "28px"),
    ("size.control.default", "32px"),
    ("size.control.touch", "44px"),
    ("size.hit-target.pointer", "28px"),
    ("size.hit-target.touch", "44px"),
    ("size.icon.lg", "20px"),
    ("size.icon.md", "16px"),
    ("size.icon.sm", "14px"),
    ("size.icon.xl", "24px"),
    ("size.panel.comfortable", "360px"),
    ("size.panel.minimum", "280px"),
    ("size.panel.wide", "480px"),
    ("size.row.compact", "28px"),
    ("size.row.default", "32px"),
    ("size.row.touch", "44px"),
    ("size.shell.commandbar", "36px"),
    ("size.shell.inspector", "360px"),
    ("size.shell.rail", "48px"),
    ("size.shell.sidebar", "196px"),
    ("size.shell.statusbar", "24px"),
    ("size.shell.topbar", "44px"),
    ("size.terminal.tab", "32px"),
    ("space.0", "0px"),
    ("space.1", "2px"),
    ("space.10", "40px"),
    ("space.11", "48px"),
    ("space.2", "4px"),
    ("space.3", "6px"),
    ("space.4", "8px"),
    ("space.5", "12px"),
    ("space.6", "16px"),
    ("space.7", "20px"),
    ("space.8", "24px"),
    ("space.9", "32px"),
    ("stroke.active", "2px"),
    ("stroke.chart", "2px"),
    ("stroke.focus", "2px"),
    ("stroke.hairline", "1px"),
    ("type.body", "15px"),
    ("type.body-lg", "17px"),
    ("type.body-sm", "13px"),
    ("type.caption", "11px"),
    ("type.console", "12.5px"),
    ("type.console-sm", "11px"),
    ("type.display", "40px"),
    ("type.h1", "32px"),
    ("type.h2", "24px"),
    ("type.h3", "20px"),
    ("type.h4", "18px"),
];

pub fn get(name: &str) -> Option<&'static str> {
    ALL.iter()
        .find_map(|(candidate, value)| (*candidate == name).then_some(*value))
}
