// TM-272: process-compose owns every standing orchestration process — the session host, the local
// NATS server, and one repository supervisor per registered repository — and restarts any that
// die. The OS keeps process-compose itself alive (os-registration.mjs). `services ensure` is the
// one idempotent entry point every caller uses: the SessionStart hook, the monitor, the lazy
// launchers, and the gateway.
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { chmod, mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import { basename, dirname, join, posix, win32 } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { PLUGIN_ROOT } from "../config.mjs";
import { invariant } from "../errors.mjs";
import { ensurePrivateDir, readJson, runFile, sha256 } from "../util.mjs";
import { probeSessionHost } from "../session/host.mjs";
import { withLock } from "../../topology/lib/lockfile.mjs";
import { localNatsEnabled, localNatsHome, prepareLocalNats } from "../../topology/lib/nats-local.mjs";
import { registrationMode, register, registrationState, start, unregister } from "./os-registration.mjs";
import { compareVersions } from "./host-copies.mjs";

export function readLock(pluginRoot = PLUGIN_ROOT) {
  return JSON.parse(readFileSync(join(pluginRoot, "services", "process-compose.lock.json"), "utf8"));
}

/** Where the binary, the launcher and the plugin pointer live. Not the state root: they are per user, not per state. */
export function dataHome({ platform = process.platform, env = process.env, home = os.homedir() } = {}) {
  if (env.AGENT_ORCHESTRATION_DATA_HOME) return env.AGENT_ORCHESTRATION_DATA_HOME;
  if (platform === "win32") return win32.join(env.LOCALAPPDATA || win32.join(home, "AppData", "Local"), "ByteDesk", "agent-orchestration");
  if (platform === "darwin") return posix.join(home, "Library", "Application Support", "bytedesk", "agent-orchestration");
  return posix.join(env.XDG_DATA_HOME || posix.join(home, ".local", "share"), "bytedesk", "agent-orchestration");
}

export function servicePaths({ stateRoot, data }) {
  const dir = join(stateRoot, "services");
  return {
    dir,
    logs: join(dir, "logs"),
    project: join(dir, "process-compose.yaml"),
    manager: join(dir, "manager.json"),
    repos: join(dir, "repos.json"),
    token: join(dir, "api-token"),
    data,
    pointer: join(data, "current.json"),
    launcher: join(data, "launcher.cjs"),
  };
}

// Runs the CURRENT plugin named by current.json, in this process: a plugin update then needs a
// process restart, never a config rewrite. `ao-topology` as the first argument selects the
// unbundled topology CLI; anything else is the bundled CLI.
export const LAUNCHER_SOURCE = `'use strict';
// Generated by \`agent-orchestration services ensure\`. Edits are overwritten.
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { pathToFileURL } = require('node:url');
const current = JSON.parse(readFileSync(join(__dirname, 'current.json'), 'utf8'));
const args = process.argv.slice(2);
if (args[0] === 'ao-topology') {
  const entry = join(current.pluginRoot, 'topology', 'cli.mjs');
  process.env.AO_TOPOLOGY_BIN ??= join(current.pluginRoot, 'bin', 'ao-topology');
  process.argv = [process.argv[0], entry, ...args.slice(1)];
  import(pathToFileURL(entry).href).catch((error) => { console.error(error); process.exitCode = 1; });
} else {
  const entry = join(current.pluginRoot, 'dist', 'cli.cjs');
  process.argv = [process.argv[0], entry, ...args];
  require(entry);
}
`;

/** An installed plugin lives at …/agent-orchestration/<sha>; a checkout has only its build fingerprint. */
export function pluginSha(pluginRoot) {
  const base = basename(pluginRoot);
  if (/^[0-9a-f]{7,64}$/.test(base)) return base;
  return typeof __AO_BUILD_FINGERPRINT__ === "undefined" ? null : __AO_BUILD_FINGERPRINT__;
}

/** What code a plugin root runs: the build fingerprint and package version, not its folder path. */
export function pluginIdentity(pluginRoot) {
  const fingerprint = typeof __AO_BUILD_FINGERPRINT__ === "undefined" ? null : __AO_BUILD_FINGERPRINT__;
  let version = typeof __AO_BUILD_VERSION__ === "undefined" ? null : __AO_BUILD_VERSION__;
  if (!version) { try { version = JSON.parse(readFileSync(join(pluginRoot, "package.json"), "utf8")).version ?? null; } catch { version = null; } }
  return { fingerprint, version };
}

export { compareVersions };

/**
 * Which plugin copy the managed services should run (TM-283). Every session's SessionStart runs
 * ensure with its own plugin root — the installed cache, the directory-marketplace source tree, or
 * an older cache in a long-lived session — so last-writer-wins would flap between equivalent copies
 * and let an old session downgrade the services. Keep the current pointer when it runs the same
 * build, never move to an older version while the current root still exists, otherwise move.
 */
export function choosePointer(previous, candidate, { exists = existsSync } = {}) {
  if (!previous?.pluginRoot || !exists(previous.pluginRoot)) return candidate;
  if (previous.node !== candidate.node) return candidate;
  if (previous.fingerprint && previous.fingerprint === candidate.fingerprint) return previous;
  if (previous.version && compareVersions(candidate.version, previous.version) < 0) return previous;
  return candidate;
}

/** Did the code the services run change? Fingerprint when both have one, else the path. */
function pointerMoved(previous, pointer) {
  if (!previous) return false;
  if (previous.node !== pointer.node) return true;
  if (previous.fingerprint && pointer.fingerprint) return previous.fingerprint !== pointer.fingerprint;
  return previous.pluginRoot !== pointer.pluginRoot || previous.sha !== pointer.sha;
}

async function writeIfChanged(path, text, mode = 0o600) {
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === text) return false;
  await mkdir(dirname(path), { recursive: true });
  const temp = `${path}.${process.pid}.tmp`;
  await writeFile(temp, text, { mode });
  await rename(temp, path);
  return true;
}

const json = (value) => `${JSON.stringify(value, null, 2)}\n`;

/** Downloads the pinned release, refuses it unless its SHA-256 matches the lock, and extracts it. */
export async function installProcessCompose({ data, platform = process.platform, arch = process.arch, lock = readLock(), fetchImpl = fetch, extract = extractArchive }) {
  const asset = lock.assets[`${platform}-${arch}`];
  invariant(asset, "AO_SERVICES_UNSUPPORTED_PLATFORM", `No pinned process-compose build for ${platform}-${arch}.`);
  const binDir = join(data, "bin", `process-compose-${lock.version}`);
  const binary = join(binDir, platform === "win32" ? "process-compose.exe" : "process-compose");
  if (existsSync(binary)) return { binary, installed: false };
  const url = `${lock.url}${asset.file}`;
  let bytes;
  try {
    const response = await fetchImpl(url, { signal: AbortSignal.timeout(120_000) });
    invariant(response.ok, "AO_SERVICES_DOWNLOAD_FAILED", `Downloading ${url} returned HTTP ${response.status}.`);
    bytes = Buffer.from(await response.arrayBuffer());
  } catch (error) {
    if (error?.code === "AO_SERVICES_DOWNLOAD_FAILED") throw error;
    invariant(false, "AO_SERVICES_DOWNLOAD_FAILED", `Downloading ${url} failed: ${error.message}`);
  }
  const actual = sha256(bytes);
  invariant(actual === asset.sha256, "AO_SERVICES_CHECKSUM_MISMATCH",
    `Refusing ${asset.file}: its SHA-256 does not match the pinned lock.`, { expected: asset.sha256, actual, url });
  await mkdir(join(data, "bin"), { recursive: true });
  const staging = await mkdtemp(join(data, "bin", ".staging-"));
  try {
    const archive = join(staging, asset.file);
    await writeFile(archive, bytes);
    await extract(archive, staging, platform);
    const extracted = join(staging, basename(binary));
    invariant(existsSync(extracted), "AO_SERVICES_EXTRACT_FAILED", `${asset.file} did not contain ${basename(binary)}.`);
    await mkdir(binDir, { recursive: true });
    await rename(extracted, binary);
    await chmod(binary, 0o755);
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
  return { binary, installed: true };
}

/** System tar: GNU and BSD tar read .tar.gz, and Windows 10+ ships bsdtar, which also reads .zip. */
async function extractArchive(archive, into, platform) {
  const tar = platform === "win32" ? join(process.env.SystemRoot || "C:\\Windows", "System32", "tar.exe") : "tar";
  await runFile(tar, ["-xf", archive, "-C", into], { timeoutMs: 60_000 });
}

/** Stable loopback port outside the ephemeral range, next to the session host's 45000-45032. */
async function pickPort() {
  for (let port = 45_100; port < 45_200; port += 1) {
    const free = await new Promise((resolve) => {
      const probe = net.createServer();
      probe.once("error", () => resolve(false));
      probe.listen(port, "127.0.0.1", () => probe.close(() => resolve(true)));
    });
    if (free) return port;
  }
  invariant(false, "AO_SERVICES_NO_PORT", "No free loopback port in 45100-45199 for the process-compose API.");
}

// ponytail: a fixed PATH so a service manager's minimal environment still finds tmux, git and
// bash; anything further is resolved to an absolute path before it reaches the project.
function servicePath({ platform, node, home }) {
  if (platform === "win32") return "";
  return [dirname(node), join(home, ".local", "bin"), ...(platform === "darwin" ? ["/opt/homebrew/bin"] : []), "/usr/local/bin", "/usr/bin", "/bin"].join(":");
}

// ponytail: callers with different values for these churn the project; none differ in practice.
const PASSED_THROUGH = ["AO_NATS_HOME", "AO_TRANSPORT", "AO_NATS_URL"];

/**
 * The process-compose project. JSON is valid YAML, so no serializer and no quoting rules: every
 * process is an argv `entrypoint`, never a shell string. Probes must be shell strings, so the
 * project's shell is node itself (`node -e <code>`) — the same on every OS, and immune to the
 * spaces and parentheses a checkout path like "bytedesk-marketplace (copy)" carries.
 */
export function renderProject({ platform = process.platform, node, launcher, stateRoot, logs, nats = null, repos = [], path = "", env = {} }) {
  const environment = [
    `AGENT_ORCHESTRATION_STATE_HOME=${stateRoot}`,
    "AGENT_ORCHESTRATION_SERVICES_MANAGED=1",
    ...(path ? [`PATH=${path}`] : []),
    ...PASSED_THROUGH.filter((name) => env[name]).map((name) => `${name}=${env[name]}`),
  ];
  const probe = (name) => ({
    exec: { command: `process.argv=[process.argv[0],'launcher',${["services", "probe", name, "--state-root", stateRoot].map((arg) => JSON.stringify(arg)).join(",")}];require(${JSON.stringify(launcher)})` },
    initial_delay_seconds: 2, period_seconds: 15, timeout_seconds: 10, failure_threshold: 3,
  });
  const rotation = { rotation: { max_size_mb: 10, max_backups: 3 } };
  const processes = {
    "session-host": {
      entrypoint: [node, launcher, "session-host", "--state-root", stateRoot],
      environment,
      availability: { restart: "always", backoff_seconds: 2 },
      readiness_probe: probe("session-host"),
      shutdown: { signal: 15, timeout_seconds: 5 },
      log_location: join(logs, "session-host.log"),
      log_configuration: rotation,
    },
  };
  if (nats) {
    processes.nats = {
      entrypoint: [nats.bin, ...nats.args],
      availability: { restart: "always", backoff_seconds: 2 },
      readiness_probe: probe("nats"),
      shutdown: { signal: 15, timeout_seconds: 5 },
      log_location: nats.log,
      log_configuration: rotation,
    };
  }
  const unsupported = [];
  for (const repo of repos) {
    const name = `supervise-${repo.key}`;
    // The supervisor drives tmux, which native Windows does not have.
    if (platform === "win32") { unsupported.push({ process: name, consumer: repo.consumer, reason: "tmux is not available on native Windows" }); continue; }
    processes[name] = {
      entrypoint: [node, launcher, "ao-topology", "supervise", "--consumer", repo.consumer],
      working_dir: repo.consumer,
      environment,
      availability: { restart: "always", backoff_seconds: 3 },
      log_location: join(logs, `${name}.log`),
      log_configuration: rotation,
    };
  }
  return {
    project: {
      version: "0.5",
      is_strict: true,
      is_tui_disabled: true,
      disable_env_expansion: true,
      shell: { shell_command: node, shell_argument: "-e" },
      processes,
    },
    unsupported,
  };
}

export function processComposeArgv({ binary, project, port, token, log }) {
  return [binary, "up", "-f", project, "-t=false", "--keep-project", "--disable-dotenv",
    "--address", "127.0.0.1", "-p", String(port), "--token-file", token, "-L", log];
}

/** The process-compose REST API (v1.122.0, src/docs/swagger.yaml). Token in X-PC-Token-Key. */
export function apiClient({ port, token }, fetchImpl = fetch) {
  const call = async (method, path, timeoutMs = 3_000) => {
    const response = await fetchImpl(`http://127.0.0.1:${port}${path}`, { method, headers: { "X-PC-Token-Key": token }, signal: AbortSignal.timeout(timeoutMs) });
    invariant(response.ok, "AO_SERVICES_API", `process-compose ${method} ${path} returned HTTP ${response.status}.`);
    return response.json().catch(() => null);
  };
  return {
    alive: () => call("GET", "/live").then(() => true, () => false),
    processes: async () => (await call("GET", "/processes"))?.data ?? [],
    reload: () => call("POST", "/project/configuration", 15_000),
    restart: (name) => call("POST", `/process/restart/${encodeURIComponent(name)}`, 15_000),
    stopProcess: (name) => call("PATCH", `/process/stop/${encodeURIComponent(name)}`, 15_000),
    stop: () => call("POST", "/project/stop", 15_000),
  };
}

async function waitFor(check, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await check()) return true;
    await delay(200);
  }
  return check();
}

async function readRepos(path) {
  const value = await readJson(path, null).catch(() => null);
  return Array.isArray(value?.repos) ? value.repos : [];
}

async function context({ pluginRoot, stateRoot, env, platform, home, node, deps }) {
  const data = dataHome({ platform, env, home });
  const paths = servicePaths({ stateRoot, data });
  const mode = deps.mode ?? await registrationMode({ platform, home, env });
  const lock = deps.lock ?? readLock(pluginRoot);
  return { data, paths, mode, lock, node };
}

/**
 * Idempotent: writes a file only when its content changed, reloads the service manager only when
 * the registration changed, starts process-compose only when it is not answering, hot-reloads the
 * project only when it changed, and restarts the processes only when the plugin they run changed.
 */
export async function ensureServices({ pluginRoot = PLUGIN_ROOT, stateRoot, env = process.env, platform = process.platform, arch = process.arch, home = os.homedir(), node = process.execPath, deps = {} } = {}) {
  const ctx = await context({ pluginRoot, stateRoot, env, platform, home, node, deps });
  const { paths, mode, lock } = ctx;
  await ensurePrivateDir(paths.logs);
  return withLock(join(paths.dir, "ensure.lock"), async () => {
    const actions = [];
    const { binary, installed } = await (deps.install ?? installProcessCompose)({ data: paths.data, platform, arch, lock, fetchImpl: deps.fetchImpl });
    if (installed) actions.push("installed");
    const previousPointer = await readJson(paths.pointer, null).catch(() => null);
    const candidate = { pluginRoot, sha: pluginSha(pluginRoot), node, ...(deps.identity ?? pluginIdentity(pluginRoot)) };
    const pointer = choosePointer(previousPointer, candidate, { exists: deps.exists ?? existsSync });
    const changed = {
      launcher: await writeIfChanged(paths.launcher, LAUNCHER_SOURCE, 0o644),
      pointer: await writeIfChanged(paths.pointer, json(pointer), 0o644),
    };
    if (!existsSync(paths.token)) await writeFile(paths.token, randomBytes(24).toString("hex"), { mode: 0o600 });
    const token = (await readFile(paths.token, "utf8")).trim();
    const previous = await readJson(paths.manager, null).catch(() => null);
    const port = previous?.port ?? await pickPort();
    const nats = localNatsEnabled(env) ? await (deps.prepareNats ?? prepareLocalNats)({ env }).catch(() => null) : null;
    const repos = (await readRepos(paths.repos)).filter((repo) => existsSync(repo.consumer));
    const path = servicePath({ platform, node, home });
    const { project, unsupported } = renderProject({ platform, node, launcher: paths.launcher, stateRoot, logs: paths.logs, nats, repos, path, env });
    changed.project = await writeIfChanged(paths.project, json(project));
    const log = join(paths.logs, "process-compose.log");
    const argv = processComposeArgv({ binary, project: paths.project, port, token: paths.token, log });
    const registration = await register({ mode, argv, logPath: log, path, home, env, servicesDir: paths.dir, run: deps.run });
    changed.registration = registration.changed;
    const manager = { mode, port, argv, registration: registration.path, project: paths.project, version: lock.version };
    changed.manager = await writeIfChanged(paths.manager, json(manager));
    const client = apiClient({ port, token }, deps.fetchImpl);
    const startArgs = { mode, argv, logPath: log, run: deps.run, spawnDetached: deps.spawnDetached };
    // A detached process-compose has no registration file to compare, so its argv stands in.
    const argvChanged = JSON.stringify(previous?.argv ?? null) !== JSON.stringify(argv);
    let alive = await client.alive();
    if (!alive) {
      await start(startArgs);
      actions.push("started");
      alive = await waitFor(client.alive, deps.startTimeoutMs ?? 15_000);
    } else if (registration.changed || (mode === "detached" && argvChanged)) {
      if (mode === "detached") { await client.stop().catch(() => {}); await waitFor(async () => !await client.alive(), 10_000); }
      await start({ ...startArgs, restart: true });
      actions.push("restarted-manager");
      alive = await waitFor(client.alive, deps.startTimeoutMs ?? 15_000);
    } else {
      if (changed.project) { await client.reload(); actions.push("reloaded"); }
      if (pointerMoved(previousPointer, pointer)) {
        for (const name of Object.keys(project.processes)) { await client.restart(name).catch(() => {}); actions.push(`restarted:${name}`); }
      }
    }
    invariant(alive, "AO_SERVICES_UNAVAILABLE", `process-compose did not answer on 127.0.0.1:${port}; see ${log}.`, { mode });
    return { ok: true, mode, port, version: lock.version, binary, actions, changed, processes: Object.keys(project.processes), unsupported,
      pointer: { pluginRoot: pointer.pluginRoot, version: pointer.version ?? null, fingerprint: pointer.fingerprint ?? null } };
  }, { timeoutMs: 300_000 }); // a concurrent first ensure may be downloading the binary
}

export async function servicesStatus({ pluginRoot = PLUGIN_ROOT, stateRoot, env = process.env, platform = process.platform, home = os.homedir(), node = process.execPath, deps = {} } = {}) {
  const { paths, mode } = await context({ pluginRoot, stateRoot, env, platform, home, node, deps });
  const manager = await readJson(paths.manager, null).catch(() => null);
  const registration = await registrationState({ mode: manager?.mode ?? mode, home, env, servicesDir: paths.dir, run: deps.run });
  const token = await readFile(paths.token, "utf8").then((text) => text.trim(), () => null);
  const client = manager?.port && token ? apiClient({ port: manager.port, token }, deps.fetchImpl) : null;
  const alive = client ? await client.alive() : false;
  const processes = alive ? (await client.processes()).map(processRow) : [];
  const repos = await readRepos(paths.repos);
  const unsupported = platform === "win32" ? repos.map((repo) => ({ process: `supervise-${repo.key}`, consumer: repo.consumer, reason: "tmux is not available on native Windows" })) : [];
  // TM-285: what the last ensure found and repaired (stale MCP servers, refreshed host copies, leaked scopes).
  const selfHeal = await readJson(join(paths.dir, "self-heal.json"), null).catch(() => null);
  return { ok: alive, registration, processCompose: { alive, port: manager?.port ?? null, version: manager?.version ?? null }, processes, unsupported, nats: { home: localNatsHome(env) }, selfHeal };
}

/** One managed process as `services status --json` reports it: scripts read the pid here, never from pgrep. */
const processRow = (p) => ({ name: p.name, pid: p.pid, state: p.status, restarts: p.restarts, ready: p.is_ready, exitCode: p.exit_code });

/**
 * TM-286: restart or stop ONE managed process by its process-compose name. Unrelated processes
 * with the same binary (a microk8s nats-server) exist on dev machines, so nothing here matches by
 * command line: the name must be one process-compose runs, or the call is refused.
 */
export async function controlProcess(action, name, { pluginRoot = PLUGIN_ROOT, stateRoot, env = process.env, platform = process.platform, home = os.homedir(), node = process.execPath, deps = {} } = {}) {
  invariant(action === "restart" || action === "stop", "AO_SERVICES_USAGE", `Unknown action ${action}. Use restart or stop.`);
  const { paths } = await context({ pluginRoot, stateRoot, env, platform, home, node, deps: { mode: "detached", lock: {}, ...deps } });
  const manager = await readJson(paths.manager, null).catch(() => null);
  const token = await readFile(paths.token, "utf8").then((text) => text.trim(), () => null);
  invariant(manager?.port && token, "AO_SERVICES_UNAVAILABLE", "The services are not installed here; run `agent-orchestration services ensure` first.");
  const client = apiClient({ port: manager.port, token }, deps.fetchImpl);
  invariant(await client.alive(), "AO_SERVICES_UNAVAILABLE", `process-compose is not answering on 127.0.0.1:${manager.port}.`);
  const list = await client.processes();
  const before = list.find((p) => p.name === name);
  invariant(before, "AO_SERVICES_UNKNOWN_PROCESS", `No managed process named ${JSON.stringify(name ?? "")}. Managed processes: ${list.map((p) => p.name).join(", ") || "none"}.`);
  if (action === "stop") {
    await client.stopProcess(name);
    return { ok: true, action, name, pid: before.pid, state: (await client.processes()).find((p) => p.name === name)?.status ?? null };
  }
  await client.restart(name);
  let after = null;
  // A restart is done when the process runs under a NEW pid; report what it is.
  await waitFor(async () => { after = (await client.processes()).find((p) => p.name === name); return Boolean(after?.pid && after.pid !== before.pid); }, deps.restartTimeoutMs ?? 15_000);
  const restarted = Boolean(after?.pid && after.pid !== before.pid);
  return { ok: restarted, action, name, previousPid: before.pid, pid: after?.pid ?? null, state: after?.status ?? null, ...(restarted ? {} : { message: `${name} did not come back under a new pid; see services status.` }) };
}

/** Readiness probes process-compose runs. Exit status is the answer. */
export async function probeService(name, { stateRoot, env = process.env } = {}) {
  if (name === "session-host") return Boolean(await probeSessionHost(stateRoot));
  if (name === "nats") {
    const state = await readJson(join(localNatsHome(env), "state.json"), null).catch(() => null);
    if (!state?.port) return false;
    return new Promise((resolve) => {
      const socket = net.connect({ host: "127.0.0.1", port: state.port }, () => { socket.destroy(); resolve(true); });
      socket.once("error", () => resolve(false));
      socket.setTimeout(2000, () => { socket.destroy(); resolve(false); });
    });
  }
  invariant(false, "AO_SERVICES_UNKNOWN_PROBE", `No probe named ${name}. Use session-host or nats.`);
}

/** Removes the OS registration and stops process-compose. Keeps the binary and all state. */
export async function uninstallServices({ pluginRoot = PLUGIN_ROOT, stateRoot, env = process.env, platform = process.platform, home = os.homedir(), node = process.execPath, deps = {} } = {}) {
  const { paths, mode } = await context({ pluginRoot, stateRoot, env, platform, home, node, deps });
  const manager = await readJson(paths.manager, null).catch(() => null);
  const token = await readFile(paths.token, "utf8").then((text) => text.trim(), () => null);
  const removed = await unregister({ mode: manager?.mode ?? mode, home, env, servicesDir: paths.dir, run: deps.run });
  let stopped = false;
  if (manager?.port && token) {
    const client = apiClient({ port: manager.port, token }, deps.fetchImpl);
    if (await client.alive()) { await client.stop().catch(() => {}); stopped = await waitFor(async () => !await client.alive(), 10_000); }
    else stopped = true;
  }
  return { ok: true, ...removed, stopped };
}
