/**
 * Repo-local launchers so `tm` is project-referenced, not a global ~/.local/bin
 * symlink to one machine's plugin path.
 *
 * Writes POSIX `sh` and Windows `cmd` wrappers under <repo>/.bytedesk/bin/.
 * They discover the plugin binary without embedding $HOME or an absolute path.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_BIN = join(dirname(fileURLToPath(import.meta.url)), "..", "bin");
const NAMES = ["tm", "tm-hook", "tm-dashboard"];

function posixScript(binName) {
  return `#!/bin/sh
# Generated by tm init. Project-local — no global install, no absolute plugin path.
set -eu
here=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
root=$(CDPATH= cd -- "$here/../.." && pwd)
run() { _cmd=$1; shift; exec node "$_cmd" "$@"; }

if [ -n "\${TM_BIN:-}" ] && [ -f "\$TM_BIN" ]; then
  run "\$TM_BIN" "$@"
fi
if [ -n "\${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "\$CLAUDE_PLUGIN_ROOT/bin/${binName}" ]; then
  run "\$CLAUDE_PLUGIN_ROOT/bin/${binName}" "$@"
fi
d="\$root"
while :; do
  if [ -f "\$d/task-management/bin/${binName}" ]; then
    run "\$d/task-management/bin/${binName}" "$@"
  fi
  nd=$(dirname "\$d")
  [ "\$nd" = "\$d" ] && break
  d="\$nd"
done
echo "task-management: plugin not found — install task-management@bytedesk or set TM_BIN" >&2
exit 127
`;
}

function cmdScript(binName) {
  return `@echo off
rem Generated by tm init. Project-local — no global install, no absolute plugin path.
setlocal EnableExtensions
set "HERE=%~dp0"
for %%I in ("%HERE%..\\..") do set "ROOT=%%~fI"
if defined TM_BIN if exist "%TM_BIN%" (
  node "%TM_BIN%" %*
  exit /b %ERRORLEVEL%
)
if defined CLAUDE_PLUGIN_ROOT if exist "%CLAUDE_PLUGIN_ROOT%\\bin\\${binName}" (
  node "%CLAUDE_PLUGIN_ROOT%\\bin\\${binName}" %*
  exit /b %ERRORLEVEL%
)
set "D=%ROOT%"
:walk
if exist "%D%\\task-management\\bin\\${binName}" (
  node "%D%\\task-management\\bin\\${binName}" %*
  exit /b %ERRORLEVEL%
)
for %%I in ("%D%\\..") do set "ND=%%~fI"
if /I "%ND%"=="%D%" goto miss
set "D=%ND%"
goto walk
:miss
echo task-management: plugin not found — install task-management@bytedesk or set TM_BIN 1>&2
exit /b 127
`;
}

export function launcherDir(root) {
  return join(root, ".bytedesk", "bin");
}

/** Write POSIX + cmd launchers. Idempotent overwrite of generated files. */
export function writeLaunchers(root) {
  if (!root) return [];
  const dir = launcherDir(root);
  mkdirSync(dir, { recursive: true });
  const written = [];
  for (const name of NAMES) {
    const sh = join(dir, name);
    const cmd = join(dir, `${name}.cmd`);
    writeFileSync(sh, posixScript(name), { mode: 0o755 });
    writeFileSync(cmd, cmdScript(name));
    written.push(sh, cmd);
  }
  return written;
}

export function pluginBin(name) {
  return join(PLUGIN_BIN, name);
}

export function launchersExist(root) {
  const dir = launcherDir(root);
  return NAMES.every((n) => existsSync(join(dir, n)) && existsSync(join(dir, `${n}.cmd`)));
}
