/**
 * Portable project-local launchers.
 *
 * The committed command surface lives inside the store at
 * <repo>/.bytedesk/task-management/bin/.  Nothing is added to a user's PATH and
 * no generated file embeds a home-directory or plugin-cache path.  Instead each
 * launcher resolves the matching plugin command at run time from explicit host
 * context, the project's marketplace declaration, or an installed-plugin
 * registry.  Resolution is per command: a tm override can never accidentally
 * launch tm-dashboard or tm-hook.
 */
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  readdirSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const NAMES = ["tm", "tm-hook", "tm-dashboard"];
const GENERATED = "Generated by task-management. Project-local; do not add this directory to PATH.";

function posixScript(binName) {
  // Dynamic import keeps this entrypoint valid whether the consumer package is CommonJS or ESM.
  // process.argv[1] is used instead of import.meta so the same source parses in both modes.
  return `#!/usr/bin/env node
// ${GENERATED}
(async () => {
  const { existsSync, readFileSync, realpathSync } = await import("node:fs");
  const { homedir } = await import("node:os");
  const { dirname, join, resolve } = await import("node:path");
  const { execFileSync, spawnSync } = await import("node:child_process");

  const binName = ${JSON.stringify(binName)};
  const self = resolve(process.argv[1]);
  const projectRoot = resolve(dirname(self), "..", "..", "..");
  const mainRoot = (() => {
    try {
      const common = execFileSync("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], {
        cwd: projectRoot,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      return common ? dirname(resolve(common)) : projectRoot;
    } catch { return projectRoot; }
  })();
  const candidates = [];
  const addRoot = (root, source) => {
    if (root) candidates.push({ target: join(resolve(root), "bin", binName), root: resolve(root), source });
  };
  const addBin = (target, source) => {
    if (target) candidates.push({ target: resolve(target), root: dirname(dirname(resolve(target))), source });
  };
  const validPlugin = (candidate) => {
    try {
      const root = realpathSync(candidate.root);
      const target = realpathSync(candidate.target);
      if (dirname(target) !== join(root, "bin") || target !== join(root, "bin", binName)) return false;
      for (const manifest of [".codex-plugin/plugin.json", ".claude-plugin/plugin.json"]) {
        try {
          if (JSON.parse(readFileSync(join(root, manifest), "utf8"))?.name === "task-management") return true;
        } catch { /* try the other manifest */ }
      }
    } catch { /* missing candidate */ }
    return false;
  };

  const commandOverride = {
    tm: process.env.TM_BIN,
    "tm-hook": process.env.TM_HOOK_BIN,
    "tm-dashboard": process.env.TM_DASHBOARD_BIN,
  }[binName];
  addBin(commandOverride, "command override");
  addRoot(process.env.TM_PLUGIN_ROOT, "TM_PLUGIN_ROOT");
  addRoot(process.env.CLAUDE_PLUGIN_ROOT, "CLAUDE_PLUGIN_ROOT");

  // The project's checked-in marketplace declaration is authoritative for a source install.
  try {
    const settings = JSON.parse(readFileSync(join(projectRoot, ".claude", "settings.json"), "utf8"));
    const source = settings?.extraKnownMarketplaces?.bytedesk?.source;
    if (source?.source === "directory" && source.path) {
      // Project marketplace paths are defined relative to the main checkout, including when
      // this committed launcher is running from a git worktree.
      addRoot(join(resolve(mainRoot, source.path), "task-management"), "project marketplace");
    }
  } catch { /* no project marketplace declaration */ }

  const addCodex = () => {
    const codexHome = process.env.CODEX_HOME || join(homedir(), ".codex");
    addRoot(join(codexHome, "plugins", "cache", "bytedesk", "task-management", "local"), "Codex plugin cache");
  };

  // Claude records exact active install paths. Prefer this project, then a user install;
  // never guess by choosing an arbitrary SHA directory from the cache.
  const addClaude = () => { try {
    const claudeHome = process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude");
    const registry = JSON.parse(readFileSync(join(claudeHome, "plugins", "installed_plugins.json"), "utf8"));
    const rows = registry?.plugins?.["task-management@bytedesk"] || [];
    const here = (() => { try { return realpathSync(projectRoot); } catch { return projectRoot; } })();
    const main = (() => { try { return realpathSync(mainRoot); } catch { return mainRoot; } })();
    const usable = rows
      .filter((row) => row?.installPath && (row.scope === "user" || (row.projectPath && (() => {
        try {
          const registered = realpathSync(row.projectPath);
          return registered === here || registered === main;
        } catch {
          const registered = resolve(row.projectPath);
          return registered === here || registered === main;
        }
      })())))
      .sort((a, b) => {
        const aProject = a.scope === "project" ? 1 : 0;
        const bProject = b.scope === "project" ? 1 : 0;
        if (aProject !== bProject) return bProject - aProject;
        return String(b.lastUpdated || b.installedAt || "").localeCompare(String(a.lastUpdated || a.installedAt || ""));
      });
    for (const row of usable) addRoot(row.installPath, "Claude " + row.scope + " plugin");
  } catch { /* Claude is absent, or has no task-management install */ } };

  // Grok installs a marketplace snapshot and records the selected plugin subdirectory in its
  // registry. The registry is the authority; directory-name globbing could select a stale copy.
  const addGrok = () => { try {
    const grokHome = process.env.GROK_HOME || join(homedir(), ".grok");
    const registry = JSON.parse(readFileSync(join(grokHome, "installed-plugins", "registry.json"), "utf8"));
    const rows = Object.values(registry?.repos || {})
      .filter((row) => row?.path && row?.plugins?.["task-management"])
      .sort((a, b) => String(b.updated_at || b.installed_at || "").localeCompare(String(a.updated_at || a.installed_at || "")));
    for (const row of rows) {
      const subdir = row.plugins["task-management"]?.subdir || row.kind?.subdir || row.marketplace?.plugin_subdir || "";
      addRoot(subdir ? join(row.path, subdir) : row.path, "Grok plugin registry");
    }
  } catch { /* Grok is absent, or has no task-management install */ } };

  // Prefer the active harness's own installation, then use a stable cross-harness fallback.
  if (process.env.GROK_SESSION_ID) { addGrok(); addCodex(); addClaude(); }
  else if (process.env.CLAUDE_CODE_SESSION_ID || process.env.CLAUDE_SESSION_ID) { addClaude(); addCodex(); addGrok(); }
  else { addCodex(); addClaude(); addGrok(); }

  const seen = new Set();
  let chosen = null;
  for (const candidate of candidates) {
    let target = candidate.target;
    try { target = realpathSync(target); } catch { /* a missing candidate is skipped below */ }
    if (target === self || seen.has(target) || !existsSync(target) || !validPlugin({ ...candidate, target })) continue;
    seen.add(target);
    chosen = { ...candidate, target };
    break;
  }
  if (!chosen) {
    process.stderr.write(
      "task-management: cannot resolve " + binName + " for " + projectRoot + ". " +
      "Enable task-management@bytedesk for this project or set TM_PLUGIN_ROOT.\\n",
    );
    process.exit(127);
  }

  const child = spawnSync(process.execPath, [chosen.target, ...process.argv.slice(2)], {
    cwd: process.cwd(),
    stdio: "inherit",
    windowsHide: true,
    env: { ...process.env, TM_LAUNCHER_SOURCE: chosen.root, TM_LAUNCHER_SOURCE_KIND: chosen.source },
  });
  if (child.error) throw child.error;
  if (child.signal) process.kill(process.pid, child.signal);
  process.exit(child.status == null ? 1 : child.status);
})().catch((err) => {
  process.stderr.write("task-management launcher: " + err.message + "\\n");
  process.exit(1);
});
`;
}

function cmdScript(binName) {
  return `@echo off\r
rem ${GENERATED}\r
node "%~dp0${binName}" %*\r
exit /b %ERRORLEVEL%\r
`;
}

export function launcherDir(root) {
  return join(root, ".bytedesk", "task-management", "bin");
}

export function legacyLauncherDir(root) {
  return join(root, ".bytedesk", "bin");
}

function expected(name) {
  return { posix: posixScript(name), cmd: cmdScript(name) };
}

function generatedFile(file) {
  try {
    const text = readFileSync(file, "utf8");
    return text.includes(GENERATED) || text.includes("Generated by tm init. Project-local");
  } catch {
    return false;
  }
}

/** Current/absent/stale/foreign state for every canonical launcher file. */
export function launcherStatus(root) {
  const dir = launcherDir(root);
  const entries = [];
  for (const name of NAMES) {
    const want = expected(name);
    for (const [kind, suffix] of [["posix", ""], ["cmd", ".cmd"]]) {
      const file = join(dir, `${name}${suffix}`);
      let state = "absent";
      if (existsSync(file)) {
        const body = readFileSync(file, "utf8");
        state = body === want[kind] ? "current" : generatedFile(file) ? "stale" : "foreign";
      }
      entries.push({ name, kind, file, state });
    }
  }
  return {
    dir,
    entries,
    current: entries.every((entry) => entry.state === "current"),
    conflicts: entries.filter((entry) => entry.state === "foreign"),
    pending: entries.filter((entry) => entry.state === "absent" || entry.state === "stale"),
  };
}

/** Write or refresh the six generated launchers without clobbering a foreign file. */
export function writeLaunchers(root) {
  if (!root) return [];
  const status = launcherStatus(root);
  if (status.conflicts.length) {
    throw new Error(`refusing to overwrite non-task-management launcher: ${status.conflicts[0].file}`);
  }
  mkdirSync(status.dir, { recursive: true });
  const written = [];
  for (const name of NAMES) {
    const want = expected(name);
    const posix = join(status.dir, name);
    const cmd = join(status.dir, `${name}.cmd`);
    if (!existsSync(posix) || readFileSync(posix, "utf8") !== want.posix) {
      writeFileSync(posix, want.posix, { mode: 0o755 });
      written.push(posix);
    }
    if (!existsSync(cmd) || readFileSync(cmd, "utf8") !== want.cmd) {
      writeFileSync(cmd, want.cmd);
      written.push(cmd);
    }
  }
  return written;
}

export function launchersExist(root) {
  return launcherStatus(root).current;
}

export function pluginBin(name) {
  return join(PLUGIN_ROOT, "bin", name);
}

/** Old committed `.bytedesk/bin/*` launchers, classified without following symlinks. */
export function legacyProjectLaunchers(root) {
  const dir = legacyLauncherDir(root);
  const entries = [];
  for (const name of NAMES) {
    for (const suffix of ["", ".cmd"]) {
      const file = join(dir, `${name}${suffix}`);
      if (!existsSync(file)) continue;
      entries.push({ file, owned: generatedFile(file) });
    }
  }
  return { dir, entries, owned: entries.filter((e) => e.owned), foreign: entries.filter((e) => !e.owned) };
}

export function removeOwnedLegacyProjectLaunchers(root) {
  const legacy = legacyProjectLaunchers(root);
  const removed = [];
  for (const entry of legacy.owned) {
    unlinkSync(entry.file);
    removed.push(entry.file);
  }
  try {
    if (existsSync(legacy.dir) && readdirSync(legacy.dir).length === 0) rmdirSync(legacy.dir);
  } catch { /* a concurrent writer or a preserved foreign file keeps the directory */ }
  return removed;
}

export function legacyGlobalDir() {
  return join(homedir(), ".local", "bin");
}

function ownedPluginTarget(target, name) {
  const normalized = resolve(target).split(sep).join("/");
  const suffix = `/task-management/bin/${name}`;
  if (!normalized.endsWith(suffix)) return false;
  const pluginRoot = PLUGIN_ROOT.split(sep).join("/");
  return normalized === `${pluginRoot}/bin/${name}`
    || normalized.includes("/.claude/plugins/cache/bytedesk/task-management/")
    || normalized.includes("/.codex/plugins/cache/bytedesk/task-management/")
    || normalized.includes("/.grok/installed-plugins/")
    || normalized.includes("/bytedesk-marketplace/task-management/bin/");
}

function wrapperTarget(file) {
  try {
    const body = readFileSync(file, "utf8");
    return /(?:exec\s+)?node\s+"([^"]+)"/.exec(body)?.[1] || null;
  } catch {
    return null;
  }
}

/** Legacy global entries we can prove were created by this plugin. Foreign names are omitted. */
export function ownedLegacyGlobalLinks(dir = legacyGlobalDir()) {
  const owned = [];
  for (const name of NAMES) {
    for (const suffix of ["", ".cmd"]) {
      const file = join(dir, `${name}${suffix}`);
      let target = null;
      try {
        const stat = lstatSync(file);
        if (stat.isSymbolicLink()) target = resolve(dirname(file), readlinkSync(file));
        else if (stat.isFile()) target = wrapperTarget(file);
      } catch {
        continue;
      }
      if (target && ownedPluginTarget(target, name)) owned.push(file);
    }
  }
  return owned;
}

export function removeOwnedLegacyGlobalLinks(dir = legacyGlobalDir()) {
  const removed = [];
  for (const file of ownedLegacyGlobalLinks(dir)) {
    unlinkSync(file);
    removed.push(file);
  }
  return removed;
}

const LEGACY_CODEX_HOOK = /(\"command\"\s*:\s*\")(?:(?:\.\/)?\.bytedesk\/bin\/)?tm-hook(?=\s|\")/g;

export function legacyCodexHooks(root) {
  const file = join(root, ".codex", "hooks.json");
  if (!existsSync(file)) return { file, count: 0 };
  const body = readFileSync(file, "utf8");
  return { file, count: [...body.matchAll(LEGACY_CODEX_HOOK)].length };
}

/** Rewrite only the legacy command prefix; preserve all other bytes and hook entries. */
export function rewriteLegacyCodexHooks(root) {
  const found = legacyCodexHooks(root);
  if (!found.count) return 0;
  const body = readFileSync(found.file, "utf8");
  const next = body.replace(LEGACY_CODEX_HOOK, `$1.bytedesk/task-management/bin/tm-hook`);
  writeFileSync(found.file, next);
  return found.count;
}
