import { after, describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { cleanup, tempStore } from "./helpers.mjs";
import {
  launcherDir,
  launcherStatus,
  launchersExist,
  legacyProjectLaunchers,
  removeOwnedLegacyProjectLaunchers,
  writeLaunchers,
} from "../../lib/launcher.mjs";
import { boardPayload } from "../../lib/dashboard-api.mjs";
import { applySettings, settingsSnapshot } from "../../lib/settings.mjs";
import { config } from "../../lib/store.mjs";

const stores = [];
after(() => cleanup(...stores));

function root(name = "tm launch ") {
  const dir = mkdtempSync(join(tmpdir(), name));
  stores.push(dir);
  return dir;
}

function fakePlugin(dir, tag) {
  const bin = join(dir, "bin");
  mkdirSync(join(dir, ".codex-plugin"), { recursive: true });
  writeFileSync(join(dir, ".codex-plugin", "plugin.json"), JSON.stringify({ name: "task-management" }));
  mkdirSync(bin, { recursive: true });
  for (const name of ["tm", "tm-hook", "tm-dashboard"]) {
    const file = join(bin, name);
    writeFileSync(file, `process.stdout.write(${JSON.stringify(`${tag}:${name}`)});\n`);
    chmodSync(file, 0o755);
  }
  return dir;
}

function run(rootDir, name, env = {}) {
  const result = spawnSync(process.execPath, [join(launcherDir(rootDir), name)], {
    cwd: rootDir,
    env: {
      PATH: process.env.PATH,
      HOME: root("tm-empty-home-"),
      ...env,
    },
    encoding: "utf8",
  });
  return result;
}

describe("project-local launchers", () => {
  it("writes six committable launchers in the task-management store", () => {
    const project = root();
    const written = writeLaunchers(project);
    assert.equal(written.length, 6);
    assert.equal(launcherDir(project), join(project, ".bytedesk", "task-management", "bin"));
    assert.equal(launchersExist(project), true);
    assert.equal(launcherStatus(project).current, true);

    const sh = readFileSync(join(launcherDir(project), "tm"), "utf8");
    const cmd = readFileSync(join(launcherDir(project), "tm.cmd"), "utf8");
    assert.match(sh, /^#!\/usr\/bin\/env node/);
    assert.match(sh, /TM_PLUGIN_ROOT/);
    assert.match(sh, /installed_plugins\.json/);
    assert.equal(sh.includes(homedir()), false, "POSIX launcher must not embed the current home");
    assert.equal(cmd.includes(homedir()), false, "cmd launcher must not embed a user profile");
    assert.match(cmd, /%~dp0tm/);
  });

  it("is idempotent and refreshes stale generated files without overwriting foreign files", () => {
    const project = root();
    writeLaunchers(project);
    assert.deepEqual(writeLaunchers(project), []);

    const tm = join(launcherDir(project), "tm");
    writeFileSync(tm, "#!/bin/sh\n# Generated by tm init. Project-local\n");
    assert.equal(launcherStatus(project).pending.length, 1);
    assert.deepEqual(writeLaunchers(project), [tm]);

    writeFileSync(tm, "#!/bin/sh\n# mine\n");
    assert.equal(launcherStatus(project).conflicts.length, 1);
    assert.throws(() => writeLaunchers(project), /refusing to overwrite/);
    assert.match(readFileSync(tm, "utf8"), /# mine/);
  });

  it("routes every command to its matching binary through TM_PLUGIN_ROOT", () => {
    const project = root();
    const plugin = fakePlugin(root("tm plugin "), "root");
    writeLaunchers(project);
    for (const name of ["tm", "tm-hook", "tm-dashboard"]) {
      const result = run(project, name, { TM_PLUGIN_ROOT: plugin });
      assert.equal(result.status, 0, result.stderr);
      assert.equal(result.stdout, `root:${name}`);
    }
  });

  it("uses command-specific overrides and never routes hook or dashboard through TM_BIN", () => {
    const project = root();
    const plugin = fakePlugin(root("tm fallback "), "fallback");
    const override = fakePlugin(root("tm override "), "override");
    writeLaunchers(project);

    assert.equal(run(project, "tm", { TM_PLUGIN_ROOT: plugin, TM_BIN: join(override, "bin", "tm") }).stdout, "override:tm");
    assert.equal(run(project, "tm-hook", { TM_PLUGIN_ROOT: plugin, TM_BIN: join(override, "bin", "tm") }).stdout, "fallback:tm-hook");
    assert.equal(run(project, "tm-dashboard", { TM_PLUGIN_ROOT: plugin, TM_BIN: join(override, "bin", "tm") }).stdout, "fallback:tm-dashboard");
    assert.equal(run(project, "tm-hook", { TM_PLUGIN_ROOT: plugin, TM_HOOK_BIN: join(override, "bin", "tm-hook") }).stdout, "override:tm-hook");
    assert.equal(run(project, "tm-dashboard", { TM_PLUGIN_ROOT: plugin, TM_DASHBOARD_BIN: join(override, "bin", "tm-dashboard") }).stdout, "override:tm-dashboard");
  });

  it("resolves the relative project marketplace declaration", () => {
    const workspace = root("tm workspace ");
    const project = join(workspace, "agent mail");
    const marketplace = join(workspace, "bytedesk marketplace");
    mkdirSync(join(project, ".claude"), { recursive: true });
    fakePlugin(join(marketplace, "task-management"), "marketplace");
    writeFileSync(join(project, ".claude", "settings.json"), JSON.stringify({
      extraKnownMarketplaces: { bytedesk: { source: { source: "directory", path: "../bytedesk marketplace" } } },
    }));
    writeLaunchers(project);
    const result = run(project, "tm");
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, "marketplace:tm");
  });

  it("resolves a relative marketplace from the main checkout when run in a git worktree", () => {
    const workspace = root("tm worktree workspace ");
    const main = join(workspace, "main");
    const worktree = join(workspace, "worktree");
    const marketplace = join(workspace, "bytedesk-marketplace");
    mkdirSync(join(main, ".claude"), { recursive: true });
    fakePlugin(join(marketplace, "task-management"), "worktree-marketplace");
    writeFileSync(join(main, ".claude", "settings.json"), JSON.stringify({
      extraKnownMarketplaces: { bytedesk: { source: { source: "directory", path: "../bytedesk-marketplace" } } },
    }));
    writeLaunchers(main);
    execFileSync("git", ["init", "-q"], { cwd: main });
    execFileSync("git", ["config", "user.name", "Launcher Test"], { cwd: main });
    execFileSync("git", ["config", "user.email", "launcher@example.com"], { cwd: main });
    execFileSync("git", ["add", "."], { cwd: main });
    execFileSync("git", ["commit", "-qm", "launcher fixture"], { cwd: main });
    execFileSync("git", ["worktree", "add", "-q", "-b", "launcher-worktree", worktree], { cwd: main });

    const result = run(worktree, "tm");
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, "worktree-marketplace:tm");
  });

  it("resolves Codex cache and Claude registry installs", () => {
    const codexProject = root();
    const codexHome = root("codex home ");
    fakePlugin(join(codexHome, "plugins", "cache", "bytedesk", "task-management", "local"), "codex");
    writeLaunchers(codexProject);
    assert.equal(run(codexProject, "tm", { CODEX_HOME: codexHome }).stdout, "codex:tm");

    const claudeProject = root();
    const claudeHome = root("claude home ");
    const install = fakePlugin(root("claude install "), "claude");
    mkdirSync(join(claudeHome, "plugins"), { recursive: true });
    writeFileSync(join(claudeHome, "plugins", "installed_plugins.json"), JSON.stringify({
      plugins: { "task-management@bytedesk": [{ scope: "project", projectPath: claudeProject, installPath: install }] },
    }));
    writeLaunchers(claudeProject);
    assert.equal(run(claudeProject, "tm-hook", { CLAUDE_CONFIG_DIR: claudeHome }).stdout, "claude:tm-hook");
  });

  it("resolves the plugin selected by the Grok registry", () => {
    const project = root();
    const grokHome = root("grok home ");
    const repo = root("grok marketplace ");
    fakePlugin(join(repo, "task-management"), "grok");
    mkdirSync(join(grokHome, "installed-plugins"), { recursive: true });
    writeFileSync(join(grokHome, "installed-plugins", "registry.json"), JSON.stringify({
      repos: { bytedesk: { path: repo, plugins: { "task-management": { subdir: "task-management" } } } },
    }));
    writeLaunchers(project);
    const result = run(project, "tm-dashboard", { GROK_HOME: grokHome });
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, "grok:tm-dashboard");
  });

  it("fails clearly when missing and does not scan arbitrary ancestors", () => {
    const workspace = root();
    const project = join(workspace, "consumer");
    mkdirSync(project, { recursive: true });
    fakePlugin(join(workspace, "task-management"), "unsafe-ancestor");
    writeLaunchers(project);
    const result = run(project, "tm");
    assert.equal(result.status, 127);
    assert.match(result.stderr, /cannot resolve tm/);
    assert.equal(result.stdout, "");
  });
});

describe("legacy project launcher cleanup", () => {
  it("removes only recognized generated launchers", () => {
    const project = root();
    const old = join(project, ".bytedesk", "bin");
    mkdirSync(old, { recursive: true });
    writeFileSync(join(old, "tm"), "#!/bin/sh\n# Generated by tm init. Project-local\n");
    writeFileSync(join(old, "tm-hook"), "#!/bin/sh\n# mine\n");

    const before = legacyProjectLaunchers(project);
    assert.equal(before.owned.length, 1);
    assert.equal(before.foreign.length, 1);
    assert.deepEqual(removeOwnedLegacyProjectLaunchers(project), [join(old, "tm")]);
    assert.equal(existsSync(join(old, "tm")), false);
    assert.equal(readFileSync(join(old, "tm-hook"), "utf8"), "#!/bin/sh\n# mine\n");
  });
});

describe("settings catalog", () => {
  it("writes launchBrowser, refuses boardId, and exposes no autolink setting", () => {
    const p = tempStore();
    stores.push(p.root);
    const snap = settingsSnapshot(p);
    assert.ok(snap.fields.some((f) => f.key === "board.launchBrowser"));
    assert.equal(snap.fields.some((f) => f.key === "plugin.autolink"), false);
    applySettings({ "board.launchBrowser": true, enforce: false }, p);
    assert.equal(config(p).board.launchBrowser, true);
    assert.equal(config(p).enforce, false);
    assert.throws(() => applySettings({ boardId: "acme/hijack" }, p), /read-only/);
  });
});

describe("board payload", () => {
  it("includes the label catalog even on an empty board", () => {
    const p = tempStore();
    stores.push(p.root);
    const cat = boardPayload(p).labelCatalog;
    assert.ok(Array.isArray(cat));
    assert.ok(cat.includes("decision:interview"));
    assert.ok(cat.includes("needs-triage"));
  });
});
