#!/usr/bin/env bash
# Generated by ao-topology. Runs agent eff264fa on codex inside its tmux pane.
set -u
cd /home/ryan/Documents/GitHub/ByteDeskAI/bytedesk-marketplace/.bytedesk/agent-orchestration/agents/eff264fa
export AO_AGENT_ID=eff264fa
export AO_AGENT_ROLE=observer
export AO_SESSION=ao-eff264fa
export AO_CONSUMER=/home/ryan/Documents/GitHub/ByteDeskAI/bytedesk-marketplace
export PATH=/home/ryan/.codex/plugins/cache/bytedesk/agent-orchestration/local/bin:/home/ryan/.volta/bin:/usr/local/bin:/usr/bin:/bin
export VOLTA_HOME=/home/ryan/.volta
printf '\033]2;%s\007' 'eff264fa · observer · codex'
exec codex --sandbox workspace-write --ask-for-approval never --add-dir /home/ryan/.local/state/bytedesk/agent-orchestration
