import assert from 'node:assert/strict';
import test from 'node:test';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { writeJson, writeText } from '../../topology/lib/util.mjs';
const exec=promisify(execFile);
test('CLI workflow preview loads resolver definition and uses recorded repository',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ao-cli-prompt-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const consumer=join(root,'repo'),caller=join(root,'wrong-repo'),runDir=join(root,'run'),dir=join(runDir,'agents','work0001');
 await Promise.all([consumer,caller,dir].map(p=>mkdir(p,{recursive:true})));
 await writeJson(join(runDir,'run.json'),{run_id:'r',consumer,session:'workflow-session',agents:[{id:'work0001',role:'worker'}]});
 await writeJson(join(dir,'prompt-agent.json'),{id:'forged-id',_dir:caller,role:'worker',instructions:'Definition-only instruction',instructions_file:'custom.md',_prompt_vars:{task:'TM-42'}});
 await writeText(join(dir,'custom.md'),'Review {{task}} carefully.');
 await writeText(join(consumer,'.bytedesk/agent-orchestration/common.md'),'Actual repository prompt');
 await writeJson(join(consumer,'.bytedesk/agent-orchestration/config.json'),{prompts:{common:'common.md'}});
 const cli=fileURLToPath(new URL('../../topology/cli.mjs',import.meta.url));
 const {stdout}=await exec(process.execPath,[cli,'prompt','preview','work0001','--run',runDir,'--consumer',caller],{env:{...process.env,XDG_CONFIG_HOME:join(root,'config')}});
 const result=JSON.parse(stdout);assert.equal(result.ok,true);assert.match(result.text,/Definition-only instruction/);assert.match(result.text,/Review TM-42 carefully/);assert.match(result.text,/Actual repository prompt/);assert.ok(!result.text.includes('forged-id'));
 assert.ok(result.sources.some(s=>s.path===join(dir,'custom.md')));
});
