import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {run,writeJson} from '../../topology/lib/util.mjs';
import {listServerPanes} from '../../topology/lib/tmux.mjs';
import {refreshPrompt} from '../../topology/lib/prompt-lifecycle.mjs';
import {superviseRepository} from '../../topology/lib/supervision.mjs';

test('supervision refreshes a live workflow instance and publishes exact membership without applying an unacknowledged change',async t=>{
 const root=await mkdtemp(join(tmpdir(),'ao-supervision-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const repo=join(root,'repo'),home=join(root,'home'),env={...process.env,AGENT_ORCHESTRATION_STATE_HOME:join(root,'state'),XDG_CONFIG_HOME:join(home,'.config')};
 await run('git',['init',repo]);
 const server=`ao-supervise-${process.pid}-${Date.now()}`;t.after(()=>run('tmux',['-L',server,'kill-server'],{allowFailure:true}));
 await run('tmux',['-L',server,'new-session','-d','-s','workflow','-c',repo,'sleep','60']);
 const binding=(await listServerPanes({tmuxServer:server}))[0];
 const conf=join(repo,'.bytedesk/agent-orchestration');await mkdir(conf,{recursive:true});
 await writeJson(join(conf,'config.json'),{prompts:{common:'./policy.md'}});await writeFile(join(conf,'policy.md'),'initial policy');
 const runDir=join(conf,'runs','run-one'),dir=join(runDir,'agents','runagent');await mkdir(dir,{recursive:true});
 const agent={id:'runagent',role:'worker',full_name:'Workflow Worker',instructions:'work',_dir:dir};
 await writeJson(join(dir,'prompt-agent.json'),agent);
 await writeJson(join(runDir,'run.json'),{run_id:'run-one',name:'workflow',run_dir:runDir,consumer:repo,session:'workflow',depth:0,parent:null,agents:[{id:agent.id,role:'worker',binding}]});
 const staged=await refreshPrompt({agent,consumer:repo,home,env});assert.equal(staged.status,'awaiting-ack');
 await writeFile(join(conf,'policy.md'),'changed policy');
 const report=await superviseRepository({consumer:repo,home,env,tmuxServer:server},{once:true});
 assert.equal(report.prompts.find(p=>p.agent===agent.id).status,'queued');
 assert.match(await readFile(join(dir,'prompt.pending.md'),'utf8'),/changed policy/);
 const state=JSON.parse(await readFile(join(dir,'prompt-state.json'),'utf8'));assert.equal(state.applied_revision,undefined);
});
